name = "sguard-sms-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace for storing SMS messages
[[kv_namespaces]]
binding = "SMS_STORAGE"
id = "2b426805a38f4403ac1e4f8a03c22d00"

# CORS settings
[env.production]
vars = { ENVIRONMENT = "production" }
